### PR TITLE
Update to 0.1.2 (old)

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender.

**Comment by ccordoba12** [comment]
Closing because I can't start CircleCI. Will reopen.

**Comment by ccordoba12** [comment]
@jakirkham, @ocefpaf, we can't build in CircleCI because the project doesn't have followers

https://circleci.com/gh/conda-forge/spyder-notebook-feedstock/17

According to CircleCI [docs](https://circleci.com/docs/1.0/cant-follow/) only project admins can start following and we're not admins.

Could you fix this? Thanks!

**Comment by jakirkham** [comment]
Could you please give it another try?

**Pull request closed without merging**
