### PR TITLE
Update to v0.3.0a0

### PR DESCRIPTION
**Pull request by jitseniesen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jitseniesen** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
Is this for an alpha release of spyder-notebook?

**Comment by jitseniesen** [comment]
> Is this for an alpha release of spyder-notebook?

Yes, I want to test that the JavaScript files and other assets for the web server are packaged correctly and that the conda package works on Windows and Mac.

**Comment by ccordoba12** [comment]
Ok, then you need to add a config file so that packages are uploaded to a different conda-forge channel instead of the main one. This is the file I added in the Spyder feedstock:

https://github.com/conda-forge/spyder-feedstock/blob/beta/recipe/conda_build_config.yaml

(You don't need the lines related to spyder-kernels, I think).

**Comment by ccordoba12** [comment]
And after doing that, you need rerender the feedstock again.

**Comment by ccordoba12** [comment]
Last thing: I think it's better to do this in a branch in this repo (you can call beta, as in the Spyder feedstock), you can keep creating alpha/beta packages in the future.

**Comment by jitseniesen** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
