### PR TITLE
Update to 0.1.2

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@jakirkham, it's still failing:

https://circleci.com/gh/conda-forge/spyder-notebook-feedstock/20

and I can't become a follower of the project.

**Comment by isuruf** [comment]
@ccordoba12, can you try again?

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender.

**Comment by ccordoba12** [comment]
Thanks @isuruf! It's working now :+1:

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender.

**Pull request merged**
