### PR TITLE
Update to 0.1.3

### PR DESCRIPTION
**Pull request by jitseniesen**
Also add myself as a maintainer

### CODE REVIEW

**Comment by jitseniesen** [comment]
@conda-forge-admin, please rerender

**Comment by jitseniesen** [comment]
@ccordoba12 Any idea why the Travis (Mac) CI build fails? It seems to have something to do with Qt WebEngine / WebKit. I don't have a Mac so it's hard for me to debug.

**Comment by ccordoba12** [comment]
Please skip the test for macOS. That problem is really unrelated to spyder-notebook.

**Comment by jitseniesen** [comment]
> Please skip the test for macOS. That problem is really unrelated to spyder-notebook.

Done. I can't merge myself since I don't have write access to the repository.

**Comment by ccordoba12** [comment]
Ok, thanks @jitseniesen!

**Pull request merged**
